# Generated by Django 5.2.1 on 2025-05-20 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('ni', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('temperatura', 'Temperatura'), ('luminosidade', 'Luminosidade'), ('umidade', 'Umidade'), ('contagem', 'Contagem')], default='temperatura', max_length=30)),
                ('mac_address', models.CharField(max_length=255)),
                ('unidade_medida', models.CharField(default='°C', max_length=3)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado')], default='ativo', max_length=20)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ambiente')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor')),
            ],
        ),
    ]
